server:
  port: 8082

spring:
  application:
    name: cart-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://49.235.39.92:3306/hm-cart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql_zaPeJ8
  cloud:
    nacos:
      server-addr: 49.235.39.92:8848

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


logging:
  level:
    com.hmall: debug
    com.hmall.api.client: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: false
  openapi:
    title: é»‘é©¬å•†åŸè´­ç‰©è½¦æœåŠ¡æ¥å£æ–‡æ¡£
    description: "é»‘é©¬å•†åŸè´­ç‰©è½¦æœåŠ¡æ¥å£æ–‡æ¡£"
    email: itheima@itcast.cn
    concat: itheima
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.cart.controller
feign:
  okhttp:
    enabled: true # ä½ å¼€å¯äº† OKHttpï¼Œè¿™å¾ˆå¥½
  client:
    config:
      default: # è¿™é‡Œé…ç½®å…¨å±€é»˜è®¤è§„åˆ™
        loggerLevel: FULL # ğŸš¨ å¼ºåˆ¶è®¾ç½®å…¨å±€æ—¥å¿—çº§åˆ«ä¸º FULL

