# 在 application-dev.yml 或 Nacos 配置中
hm:
  db:
    host: 192.168.1.50      # 对应 ${hm.db.host}
    user: admin             # 对应 ${hm.db.user}
    password: newPassword   # 对应 ${hm.db.password}
    db: hm-cart                # 对应 ${hm.db.db}，这个你之前没给默认值，这里必须配置！
spring:
  application:
    name: cart-service
